--
-- These queries create OLTP logging tables for a Oracle database
--
--
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER pentaho_dilogs IDENTIFIED BY "password" default tablespace pentaho_tablespace quota unlimited on pentaho_tablespace temporary tablespace temp quota 5M on system;
GRANT RESOURCE, CREATE SESSION, CREATE PROCEDURE, CREATE TABLE TO pentaho_dilogs;

-- Job log table
--

CREATE TABLE pentaho_dilogs.job_logs
(
  ID_JOB INTEGER
, CHANNEL_ID VARCHAR(255)
, JOBNAME VARCHAR(255)
, STATUS VARCHAR(15)
, LINES_READ NUMBER(38)
, LINES_WRITTEN NUMBER(38)
, LINES_UPDATED NUMBER(38)
, LINES_INPUT NUMBER(38)
, LINES_OUTPUT NUMBER(38)
, LINES_REJECTED NUMBER(38)
, ERRORS NUMBER(38)
, STARTDATE TIMESTAMP
, ENDDATE TIMESTAMP
, LOGDATE TIMESTAMP
, DEPDATE TIMESTAMP
, REPLAYDATE TIMESTAMP
, LOG_FIELD CLOB
, EXECUTING_SERVER VARCHAR(255)
, EXECUTING_USER VARCHAR(255)
, START_JOB_ENTRY VARCHAR(255)
, CLIENT VARCHAR(255)
)
;
CREATE INDEX pentaho_dilogs.IDX_job_logs_1 ON pentaho_dilogs.job_logs(ID_JOB)
;
CREATE INDEX pentaho_dilogs.IDX_job_logs_2 ON pentaho_dilogs.job_logs(ERRORS, STATUS, JOBNAME)
;


-- Job entry log table
--

CREATE TABLE pentaho_dilogs.jobentry_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE TIMESTAMP
, TRANSNAME VARCHAR(255)
, STEPNAME VARCHAR(255)
, LINES_READ NUMBER(38)
, LINES_WRITTEN NUMBER(38)
, LINES_UPDATED NUMBER(38)
, LINES_INPUT NUMBER(38)
, LINES_OUTPUT NUMBER(38)
, LINES_REJECTED NUMBER(38)
, ERRORS NUMBER(38)
, "RESULT" CHAR(5)
, NR_RESULT_ROWS NUMBER(38)
, NR_RESULT_FILES NUMBER(38)
, LOG_FIELD CLOB
, COPY_NR INTEGER
)
;
CREATE INDEX pentaho_dilogs.IDX_jobentry_logs_1 ON pentaho_dilogs.jobentry_logs(ID_BATCH)
;


-- Logging channel log table
--

CREATE TABLE pentaho_dilogs.channel_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE TIMESTAMP
, LOGGING_OBJECT_TYPE VARCHAR(255)
, OBJECT_NAME VARCHAR(255)
, OBJECT_COPY VARCHAR(255)
, REPOSITORY_DIRECTORY VARCHAR(255)
, FILENAME VARCHAR(255)
, OBJECT_ID VARCHAR(255)
, OBJECT_REVISION VARCHAR(255)
, PARENT_CHANNEL_ID VARCHAR(255)
, ROOT_CHANNEL_ID VARCHAR(255)
)
;
CREATE TABLE pentaho_dilogs.checkpoint_logs
(
  ID_JOB_RUN INTEGER
, ID_JOB INTEGER
, JOBNAME VARCHAR(255)
, NAMESPACE VARCHAR(255)
, CHECKPOINT_NAME VARCHAR(255)
, CHECKPOINT_COPYNR SMALLINT
, ATTEMPT_NR INTEGER
, JOB_RUN_START_DATE TIMESTAMP
, LOGDATE TIMESTAMP
, RESULT_XML CLOB
, PARAMETER_XML CLOB
)
;
CREATE INDEX pentaho_dilogs.IDX_checkpoint_logs_1 ON pentaho_dilogs.checkpoint_logs(ID_JOB_RUN)
;
CREATE INDEX pentaho_dilogs.IDX_checkpoint_logs_2 ON pentaho_dilogs.checkpoint_logs(JOBNAME, NAMESPACE)
;


-- Transformation log table
--

CREATE TABLE pentaho_dilogs.trans_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, TRANSNAME VARCHAR(255)
, STATUS VARCHAR(15)
, LINES_READ NUMBER(38)
, LINES_WRITTEN NUMBER(38)
, LINES_UPDATED NUMBER(38)
, LINES_INPUT NUMBER(38)
, LINES_OUTPUT NUMBER(38)
, LINES_REJECTED NUMBER(38)
, ERRORS NUMBER(38)
, STARTDATE TIMESTAMP
, ENDDATE TIMESTAMP
, LOGDATE TIMESTAMP
, DEPDATE TIMESTAMP
, REPLAYDATE TIMESTAMP
, LOG_FIELD CLOB
, EXECUTING_SERVER VARCHAR(255)
, EXECUTING_USER VARCHAR(255)
, CLIENT VARCHAR(255)
)
;
CREATE INDEX pentaho_dilogs.IDX_trans_logs_1 ON pentaho_dilogs.trans_logs(ID_BATCH)
;
CREATE INDEX pentaho_dilogs.IDX_trans_logs_2 ON pentaho_dilogs.trans_logs(ERRORS, STATUS, TRANSNAME)
;

-- Step log table
--

CREATE TABLE pentaho_dilogs.step_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE TIMESTAMP
, TRANSNAME VARCHAR(255)
, STEPNAME VARCHAR(255)
, STEP_COPY SMALLINT
, LINES_READ NUMBER(38)
, LINES_WRITTEN NUMBER(38)
, LINES_UPDATED NUMBER(38)
, LINES_INPUT NUMBER(38)
, LINES_OUTPUT NUMBER(38)
, LINES_REJECTED NUMBER(38)
, ERRORS NUMBER(38)
, LOG_FIELD CLOB
)
;


-- Step performance log table
--

CREATE TABLE pentaho_dilogs.transperf_logs
(
  ID_BATCH INTEGER
, SEQ_NR INTEGER
, LOGDATE TIMESTAMP
, TRANSNAME VARCHAR(255)
, STEPNAME VARCHAR(255)
, STEP_COPY INTEGER
, LINES_READ NUMBER(38)
, LINES_WRITTEN NUMBER(38)
, LINES_UPDATED NUMBER(38)
, LINES_INPUT NUMBER(38)
, LINES_OUTPUT NUMBER(38)
, LINES_REJECTED NUMBER(38)
, ERRORS NUMBER(38)
, INPUT_BUFFER_ROWS NUMBER(38)
, OUTPUT_BUFFER_ROWS NUMBER(38)
)
;


-- Metrics log table
--

CREATE TABLE pentaho_dilogs.metrics_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE TIMESTAMP
, METRICS_DATE TIMESTAMP
, METRICS_CODE VARCHAR(255)
, METRICS_DESCRIPTION VARCHAR(255)
, METRICS_SUBJECT VARCHAR(255)
, METRICS_TYPE VARCHAR(255)
, METRICS_VALUE NUMBER(38)
)
;
