--
-- These queries create OLTP logging tables for a MySQL database
--
-- 

CREATE DATABASE IF NOT EXISTS pentaho_dilogs;
grant all on pentaho_dilogs.* to 'hibuser'@'%';

USE pentaho_dilogs;

-- Job log table
--

CREATE TABLE job_logs
(
  ID_JOB INTEGER
, CHANNEL_ID VARCHAR(255)
, JOBNAME VARCHAR(255)
, `STATUS` VARCHAR(15)
, LINES_READ BIGINT(38)
, LINES_WRITTEN BIGINT(38)
, LINES_UPDATED BIGINT(38)
, LINES_INPUT BIGINT(38)
, LINES_OUTPUT BIGINT(38)
, LINES_REJECTED BIGINT(38)
, `ERRORS` BIGINT(38)
, STARTDATE DATETIME
, ENDDATE DATETIME
, LOGDATE DATETIME
, DEPDATE DATETIME
, REPLAYDATE DATETIME
, LOG_FIELD LONGTEXT
, EXECUTING_SERVER VARCHAR(255)
, EXECUTING_USER VARCHAR(255)
, START_JOB_ENTRY VARCHAR(255)
, `CLIENT` VARCHAR(255)
)
;
CREATE INDEX IDX_job_logs_1 ON job_logs(ID_JOB)
;
CREATE INDEX IDX_job_logs_2 ON job_logs(ERRORS, STATUS, JOBNAME)
;



-- Job entry log table
--

CREATE TABLE jobentry_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE DATETIME
, TRANSNAME VARCHAR(255)
, STEPNAME VARCHAR(255)
, LINES_READ BIGINT(38)
, LINES_WRITTEN BIGINT(38)
, LINES_UPDATED BIGINT(38)
, LINES_INPUT BIGINT(38)
, LINES_OUTPUT BIGINT(38)
, LINES_REJECTED BIGINT(38)
, ERRORS BIGINT(38)
, `RESULT` CHAR(5)
, NR_RESULT_ROWS BIGINT(38)
, NR_RESULT_FILES BIGINT(38)
, LOG_FIELD LONGTEXT
, COPY_NR INTEGER
)
;
CREATE INDEX IDX_jobentry_logs_1 ON jobentry_logs(ID_BATCH)
;


-- Logging channel log table
--

CREATE TABLE channel_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE DATETIME
, LOGGING_OBJECT_TYPE VARCHAR(255)
, OBJECT_NAME VARCHAR(255)
, OBJECT_COPY VARCHAR(255)
, REPOSITORY_DIRECTORY VARCHAR(255)
, FILENAME VARCHAR(255)
, OBJECT_ID VARCHAR(255)
, OBJECT_REVISION VARCHAR(255)
, PARENT_CHANNEL_ID VARCHAR(255)
, ROOT_CHANNEL_ID VARCHAR(255)
)
;
CREATE TABLE checkpoint_logs
(
  ID_JOB_RUN INTEGER
, ID_JOB INTEGER
, JOBNAME VARCHAR(255)
, NAMESPACE VARCHAR(255)
, CHECKPOINT_NAME VARCHAR(255)
, CHECKPOINT_COPYNR SMALLINT
, ATTEMPT_NR INTEGER
, JOB_RUN_START_DATE DATETIME
, LOGDATE DATETIME
, RESULT_XML LONGTEXT
, PARAMETER_XML LONGTEXT
)
;
CREATE INDEX IDX_checkpoint_logs_1 ON checkpoint_logs(ID_JOB_RUN)
;
CREATE INDEX IDX_checkpoint_logs_2 ON checkpoint_logs(JOBNAME, NAMESPACE)
;


-- Transformation log table
--

CREATE TABLE trans_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, TRANSNAME VARCHAR(255)
, `STATUS` VARCHAR(15)
, LINES_READ BIGINT(38)
, LINES_WRITTEN BIGINT(38)
, LINES_UPDATED BIGINT(38)
, LINES_INPUT BIGINT(38)
, LINES_OUTPUT BIGINT(38)
, LINES_REJECTED BIGINT(38)
, `ERRORS` BIGINT(38)
, STARTDATE DATETIME
, ENDDATE DATETIME
, LOGDATE DATETIME
, DEPDATE DATETIME
, REPLAYDATE DATETIME
, LOG_FIELD LONGTEXT
, EXECUTING_SERVER VARCHAR(255)
, EXECUTING_USER VARCHAR(255)
, `CLIENT` VARCHAR(255)
)
;
CREATE INDEX IDX_trans_logs_1 ON trans_logs(ID_BATCH)
;
CREATE INDEX IDX_trans_logs_2 ON trans_logs(ERRORS, STATUS, TRANSNAME)
;

-- Step log table
--

CREATE TABLE step_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE DATETIME
, TRANSNAME VARCHAR(255)
, STEPNAME VARCHAR(255)
, STEP_COPY SMALLINT
, LINES_READ BIGINT(38)
, LINES_WRITTEN BIGINT(38)
, LINES_UPDATED BIGINT(38)
, LINES_INPUT BIGINT(38)
, LINES_OUTPUT BIGINT(38)
, LINES_REJECTED BIGINT(38)
, `ERRORS` BIGINT(38)
, LOG_FIELD LONGTEXT
)
;


-- Step performance log table
--

CREATE TABLE transperf_logs
(
  ID_BATCH INTEGER
, SEQ_NR INTEGER
, LOGDATE DATETIME
, TRANSNAME VARCHAR(255)
, STEPNAME VARCHAR(255)
, STEP_COPY INTEGER
, LINES_READ BIGINT(38)
, LINES_WRITTEN BIGINT(38)
, LINES_UPDATED BIGINT(38)
, LINES_INPUT BIGINT(38)
, LINES_OUTPUT BIGINT(38)
, LINES_REJECTED BIGINT(38)
, `ERRORS` BIGINT(38)
, INPUT_BUFFER_ROWS BIGINT(38)
, OUTPUT_BUFFER_ROWS BIGINT(38)
)
;


-- Metrics log table
--

CREATE TABLE metrics_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE DATETIME
, METRICS_DATE DATETIME
, METRICS_CODE VARCHAR(255)
, METRICS_DESCRIPTION VARCHAR(255)
, METRICS_SUBJECT VARCHAR(255)
, METRICS_TYPE VARCHAR(255)
, METRICS_VALUE BIGINT(38)
)
;
