version: '3.6'

services:
  pentahoServer:
    image: pentaho/pentaho-server:${PENTAHO_VERSION:-8.3.0.0}
    build:
      context: "./"
    hostname: pentahoServer
    ports:
      - "${PORT}:8080"
      - "8044:8044"
      - "1521:1521"
      - "5500:5500"
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 5g
    volumes:
      #Bindings
      - "${OVERRIDE_FOLDER}/:/docker-entrypoint-init"
    environment:
      - CATALINA_OPTS=>-
        -Dfile.encoding=utf8
        -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8044
        -Dpentaho.installed.licenses.file=/run/secrets/pentaho_license
        -XX:+UseConcMarkSweepGC
        -XX:+ExplicitGCInvokesConcurrent
        -XX:+CMSClassUnloadingEnabled
        -XX:+AggressiveOpts
        -Xmx4g
    secrets:
      - pentaho_license
    depends_on:
      repository:
        condition: service_healthy
    command: [ "sh", "./tomcat/bin/catalina.sh", "run" ]

  repository:
    image: ${DOCKER_DATABASE_IMAGE}
    environment:
      - ORACLE_PWD=password
      - ORACLE_SID=XE
      #- ORACLE_PDB=XE
    volumes:
      - "./db_init_oracle:/opt/oracle/scripts/startup"
      - repository-data:/opt/oracle/oradata

volumes:
  repository-data:
  server_jackrabbit:

secrets:
  pentaho_license:
    file: "./local/installedLicenses.xml"

